export const SET_STUDENT_INFO = "SET_STUDENT_INFO";
export const SET_TOP_STUDENT = "SET_TOP_STUDENT";
export const OVERALL_RATING = "OVERALL_RATING";
export const ADD_COMMENT = "ADD_COMMENT";
export const ON_ERROR = "ON_ERROR";